{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c78dddae",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "from sklearn.preprocessing import LabelEncoder, MinMaxScaler, OneHotEncoder\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.multioutput import MultiOutputClassifier\n",
    "from sklearn.metrics import classification_report\n",
    "import joblib\n",
    "model = joblib.load('microbial_model.pkl')\n",
    "\n",
    "# Load the trained model\n",
    "#@st.cache(allow_output_mutation=True)\n",
    "#def load_model():\n",
    " #   with open('microbial_model.pkl', 'rb') as file:\n",
    "  #      model = pickle.load(file)\n",
    "   # return model\n",
    "\n",
    "# Load the model, scaler, and encoder\n",
    "#model = load_model()\n",
    "#scaler = load_scaler()\n",
    "#encoder = load_encoder()\n",
    "\n",
    "# Streamlit app layout\n",
    "st.title(\"Microbial Organisms Multi-Label Prediction App\")\n",
    "\n",
    "# Example: Input fields (customize these based on your feature space)\n",
    "st.header(\"Input Predicting Variables\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "6b3828cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-09-17 13:23:19.374 Session state does not function when running a script without `streamlit run`\n"
     ]
    }
   ],
   "source": [
    "# Collecting input values for all feature columns\n",
    "fish_sample = st.text_input(\"Fish Sample\", \"\")\n",
    "colour = st.text_input(\"Colour\", \"\")\n",
    "odour = st.text_input(\"Odour\", \"\")\n",
    "texture = st.text_input(\"Texture\", \"\")\n",
    "flavour = st.text_input(\"Flavour\", \"\")\n",
    "appearance = st.text_input(\"Appearance\", \"\")\n",
    "insect_invasion = st.text_input(\"Insect Invasion\", \"\")\n",
    "overall_acceptability = st.text_input(\"Overall Acceptability\", \"\")\n",
    "market = st.text_input(\"Market\", \"\")\n",
    "state = st.text_input(\"State\", \"\")\n",
    "tba = st.text_input(\"TBA\", \"\")\n",
    "pbc = st.text_input(\"PBC\", \"\")\n",
    "tfc = st.text_input(\"TFC\", \"\")\n",
    "pigmentation = st.text_input(\"Pigmentation\", \"\")\n",
    "elevation = st.text_input(\"Elevation\", \"\")\n",
    "texture_1 = st.text_input(\"Texture.1\", \"\")\n",
    "margin = st.text_input(\"Margin\", \"\")\n",
    "shape = st.text_input(\"Shape\", \"\")\n",
    "optical_density = st.text_input(\"Optical Density\", \"\")\n",
    "pigmentation_1 = st.text_input(\"Pigmentation.1\", \"\")\n",
    "elevation_1 = st.text_input(\"Elevation.1\", \"\")\n",
    "texture_2 = st.text_input(\"Texture.2\", \"\")\n",
    "margin_1 = st.text_input(\"Margin.1\", \"\")\n",
    "shape_1 = st.text_input(\"Shape.1\", \"\")\n",
    "optical_density_1 = st.text_input(\"Optical Density.1\", \"\")\n",
    "pigmentation_2 = st.text_input(\"Pigmentation.2\", \"\")\n",
    "elevation_2 = st.text_input(\"Elevation.2\", \"\")\n",
    "texture_3 = st.text_input(\"Texture.3\", \"\")\n",
    "margin_2 = st.text_input(\"Margin.2\", \"\")\n",
    "shape_2 = st.text_input(\"Shape.2\", \"\")\n",
    "optical_density_2 = st.text_input(\"Optical Density.2\", \"\")\n",
    "ph = st.number_input(\"pH\", min_value=0.0)\n",
    "lipid_oxidation = st.number_input(\"Lipid Oxidation (MDA) mg/L\", min_value=0.0)\n",
    "moisture_content = st.number_input(\"Moisture Content (%)\", min_value=0.0)\n",
    "protein = st.number_input(\"Protein (%)\", min_value=0.0)\n",
    "fat = st.number_input(\"Fat (%)\", min_value=0.0)\n",
    "ash = st.number_input(\"Ash (%)\", min_value=0.0)\n",
    "\n",
    "# Combine input data into a DataFrame\n",
    "input_data = pd.DataFrame({\n",
    "    'Fish sample': [fish_sample],\n",
    "    'Colour': [colour],\n",
    "    'Odour': [odour],\n",
    "    'Texture': [texture],\n",
    "    'Flavour': [flavour],\n",
    "    'Appearance': [appearance],\n",
    "    'Insect Invasion': [insect_invasion],\n",
    "    'Overall Acceptability': [overall_acceptability],\n",
    "    'Market': [market],\n",
    "    'State': [state],\n",
    "    'TBA': [tba],\n",
    "    'PBC': [pbc],\n",
    "    'TFC': [tfc],\n",
    "    'Pigmentation': [pigmentation],\n",
    "    'Elevation': [elevation],\n",
    "    'Texture.1': [texture_1],\n",
    "    'Margin': [margin],\n",
    "    'Shape': [shape],\n",
    "    'Optical Density': [optical_density],\n",
    "    'Pigmentation.1': [pigmentation_1],\n",
    "    'Elevation.1': [elevation_1],\n",
    "    'Texture.2': [texture_2],\n",
    "    'Margin.1': [margin_1],\n",
    "    'Shape.1': [shape_1],\n",
    "    'Optical Density.1': [optical_density_1],\n",
    "    'Pigmentation.2': [pigmentation_2],\n",
    "    'Elevation.2': [elevation_2],\n",
    "    'Texture.3': [texture_3],\n",
    "    'Margin.2': [margin_2],\n",
    "    'Shape.2': [shape_2],\n",
    "    'Optical Density.2': [optical_density_2],\n",
    "    'pH': [ph],\n",
    "    'Lipid oxidation': [lipid_oxidation],\n",
    "    'Moisture Content': [moisture_content],\n",
    "    'Protein': [protein],\n",
    "    'Fat': [fat],\n",
    "    'Ash': [ash]\n",
    "})\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b5a8368d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Preprocessing inputs before prediction\n",
    "if st.button(\"Predict\"):\n",
    "    try:\n",
    "        # Handle preprocessing here\n",
    "        # Apply scaling to numerical fields (if necessary)\n",
    "        numeric_fields = input_data.select_dtypes(include=np.number)\n",
    "        input_data_scaled = scaler.transform(numeric_fields)\n",
    "        \n",
    "        # Apply encoding to categorical fields (LabelEncoder for input fields)\n",
    "        df_to_encode = input_data.select_dtypes(include='object').astype(str)\n",
    "        le = LabelEncoder()\n",
    "        for column in df_to_encode.columns:\n",
    "            df_to_encode[column] = le.fit_transform(df_to_encode[column])\n",
    "        \n",
    "        # Combine the scaled and encoded data\n",
    "        input_preprocessed = np.hstack([input_data_scaled, df_to_encode])\n",
    "        \n",
    "        # Convert preprocessed input back into a DataFrame\n",
    "        input_preprocessed_df = pd.DataFrame(input_preprocessed, columns=input_data.columns)\n",
    "\n",
    "        # Make predictions with the preprocessed data\n",
    "        prediction = model.predict(input_preprocessed_df)\n",
    "\n",
    "        # Decode the multilabel prediction (OneHotEncoder reverse transformation)\n",
    "        predicted_labels = encoder.inverse_transform(prediction)\n",
    "\n",
    "        # Display the prediction\n",
    "        st.subheader(\"Predicted Microbial Organisms:\")\n",
    "        st.write(predicted_labels)\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"An error occurred during prediction: {e}\")\n",
    "\n",
    "# Footer\n",
    "st.write(\"This application uses a multi-label classification model to predict microbial organisms based on input features.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bed20c5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
